services:
  aws:
    image: gresau/localstack-persist:4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      retries: 5
      timeout: 10s
      start_period: 10s
    ports:
      - "4566:4566"
    volumes:
      - localstack_s3_data:/persisted-data
    environment:
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
  initialize:
    image: ${AWS_ACCOUNT_ID:-123456789012}.dkr.ecr.${AWS_REGION:-us-east-1}.amazonaws.com/hatchet/globi:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: src/globi/worker/Dockerfile
      args:
        - EP_VERSION=${EP_VERSION:-22.2.0}
        - PYTHON_VERSION=${PYTHON_VERSION:-3.12}
    command:
      ["uv", "run", "python", "src/globi/worker/initialize/local_aws_init.py"]
    env_file:
      - .env
      - .env.local.aws
      - .env.scythe.storage
    depends_on:
      aws:
        condition: service_healthy
  simulations:
    depends_on:
      initialize:
        # wait for initialize to have completed
        condition: service_completed_successfully
  fanouts:
    depends_on:
      initialize:
        # wait for initialize to have completed
        condition: service_completed_successfully

volumes:
  localstack_s3_data:
